### ISSUE TITLE
Strikethrough markdown does not work

### ISSUE THREAD

**Issue by mistwyrm** [code-with-sam/goodbook.reviews#10]
Strikethrough markdown (\~\~strike\~\~) does not work

**Comment by code-with-sam** [comment]
~~strike-through~~ should work as expected now. 
<img width="689" alt="screen shot 2018-05-09 at 00 59 06" src="https://user-images.githubusercontent.com/34964560/39788838-3427066a-5324-11e8-8052-add0d9f752ce.png">
